"""
This module contains the NameManager class for keeping track of all the
variables within a system. The information kept within the name registry in a
NameManager object is used to ensure components are given unique names to
correctly reference variables within calculations.
"""


class NameManager:
    """
    This is the name manager for system components. It keep tracks of the
    variables registered in the system, so the system's components can
    correctly mix together the different component code strings.

    The name registry attribute "_sys_var_names" keeps track of how many times
    a variable has been used in a system to make sure repeated generated
    variable names are given a unique name within the system.
    """

    def __init__(self):

        self._sys_var_names = {}  # Name registry for a system

    def generateComponentName(self, comp_obj):
        """
        Generate a name for a component if one wasn't assigned to it. The name
        is generated by using the default name of the component, it's container
        system and the amount of times this combination of names has been
        registered in the system's name manager.
        """

        comp_obj_sys = comp_obj.sys  # Component's system container
        main_sys = comp_obj_sys.main_sys  # System that contains all components
        is_a_system = hasattr(comp_obj, "sys_comps")  # If component is a system

        comp_name = comp_obj.default_name
        if not (comp_obj_sys is main_sys or is_a_system):
            comp_name += "_" + comp_obj_sys.name
        return self._registerComponentName(comp_name)

    def verifyCustomComponentName(self, comp_name):
        """
        This will verify if the custom component name was registered in the
        name manager. If it was registered, it will produce a NameError
        indicating this.
        """

        if comp_name in self._sys_var_names:
            raise NameError(f'The name "{comp_name}" was registered more than once.')
        return self._registerComponentName(comp_name)

    def _registerComponentName(self, comp_name):

        if comp_name in self._sys_var_names:  # Update name registry
            new_comp_name = comp_name + "_" + str(self._sys_var_names[comp_name])
            self._sys_var_names[comp_name] += 1
            return new_comp_name

        # Register name
        self._sys_var_names[comp_name] = 1
        return comp_name
